### ISSUE TITLE
请问编译时的linux内核版本是什么？

### ISSUE THREAD

**Issue by wanyingwe** [jacobchencc/panfrost#1]
我按照这个流程操作了一遍并没有生效，从第一步编译内核后的启动信息就没有panfrost的内容。
我怀疑是否是内核不同，你的内核已经包含了有panfrost的内容而我的没有导致的？
使用命令lsmod | grep panfrost没有输出信息，我的内核版本是4.19.232。

希望大佬给回复一下~

**Comment by jacobchencc** [comment]
panfrost支持Mali midgard/bifrost系列GPU，初始版本合并至linux 5.1.0-rc2。该仓库基于rockchip发布的5.10及6.1 linux内核测试。如果要反向移植到4.19.232版本linux上，drm驱动框架差异较大，预计会遇到一些阻力。

**Comment by wanyingwe** [comment]
> panfrost支持Mali midgard/bifrost系列GPU，初始版本合并至linux 5.1.0-rc2。该仓库基于rockchip发布的5.10及6.1 linux内核测试。如果要反向移植到4.19.232版本linux上，drm驱动框架差异较大，预计会遇到一些阻力。

我后来搞懂了，3588的GPU驱动，Linux内核主线支持要6.1以后了，3568的GPU驱动Linux内核5.10开始支持了，反向移植太难了，就用新的内核版本了
